title: "Derek Lim"
author: "Default Author Name"
description: "Derek Lim is an MD, entrepreneur and current Masters of Clinical Informatics Management candidate at Stanford University. At Stanford, he is Co-President of the Graduate Healthcare Club and is a consultant for the Stanford Healthcare Consulting Group.
He is currently focused on improving mental health accessibility and is building a mobile application that will be the ‘Duolingo for mental health.’ 

Derek’s previous research looked at the real-world efficacy of a novel self-guided course for the management of chronic pain. He is currently researching the use of clinical informatics in identifying modifiable bottlenecks in the emergency department, reducing the length of stay for patients. 

Derek grew up between Singapore and Australia and holds a Bachelor of Medical Studies, Doctor of Medicine (Bmed/MD) from the University of New South Wales and started his residency at St Vincent’s Hospital Sydney.
He loves meeting other entrepreneurs and innovators with ambitious goals and can best be reached on Linkedin." # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "example@mail.com"
twitter_username: "twitteruser"
github_username: "githubuser"
linkedin_username: "linkedinuser"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
